project:
  type: website

website:
  title: "RinPharmaDiversityAlliance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - united
      - custom.scss
    css: styles.css
    toc: true

editor: visual

