project:
  type: website

website:
  title: "RinPharmaDiversityAlliance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: posts.qmd
        text: Posts
    right:
      - href: about.qmd
        text: About
     

format:
  html:
    email-obfuscation: javascript
    theme:
      - united
      - custom.scss
    css: styles.css
    toc: true

editor: visual

