---
title: "R/Pharma Hackathon 2024"
---

Do you identify as underrepresented and would you like to get involved in open source projects? Then please keep reading… this hackathon may be for you! 

During our early Diversity Alliance meetings we discussed how we might be able to minimise barriers to entry in the open-source community (from opening issues to making your first pull request). We found that a common denominator in our Alliance members: someone helped me get started. 

We would like to use this hackathon to help you get started. Join mentors from the R/Pharma community to learn about how to contribute to open source projects. You'll work with mentors in small groups, tackling open issues in real projects.

At the end of this hackathon we hope you will have expanded your network in our community and having gained increased familiarity with making contributions in the open-source space. 


# Participant Information

Welcome to the 2024 hackathon! Thank you for signing up. This event is aimed at individuals who have not contributed to the open source much but are looking for a way to start giving back. This event will be run on October 21st at 16:00 GMT (11:00 EST) and will last 4 hours.

While not required, it will be helpful to have some background R knowledge.

Prior to the hackathon please make to do the following:

-   Create Github account

-   Connect github account to either your local computer or a posit cloud instance


# Mentors Information 

Make sure to join the mentors slack channel to get the most up to date information. 
Prior to the day, make sure you have looked at your issues and are confident that you can help will all the issues you have been assigned. If you have any questions please reach out on the slack channel. 
